"""Falsifier A1: Principal closed-orbit Jacobian of the Apollonian IFS.

Hypothesis under test:
  The principal periodic orbit of the Apollonian dynamics on the
  classical seed (-1, 2, 2, 3) has Jacobian product equal to phi^{-5}.

  This is the *most direct* test of conj:phi5-relaxation read as a
  statement about closed-orbit dynamics: in transfer-operator
  language, the spectral gap of L_phi is the inverse of the smallest
  non-trivial Jacobian among periodic orbits, and the principal
  closed orbit is the shortest one with non-degenerate Jacobian.

Setup:
  Seed (-1, 2, 2, 3): outer circle k=-1 plus three inner circles
    C_1 = (centre (-1/2, 0),   radius 1/2,   k = 2)
    C_2 = (centre (+1/2, 0),   radius 1/2,   k = 2)
    C_3 = (centre (0,   2/3),  radius 1/3,   k = 3)

  IFS branches: T_i is anti-conformal inversion through C_i:
    T_i(z) = c_i + r_i^2 / conj(z - c_i)
    |T_i'(z)| = r_i^2 / |z - c_i|^2.

  C_1, C_2, C_3 are mutually externally tangent (they bound the
  central interstice of the seed gasket).  Length-2 words T_i T_j
  with i != j are therefore parabolic (fix the tangency point with
  derivative magnitude 1) and contribute no spectral gap.

  Length-3 word T_1 T_2 T_3 is anti-conformal (composition of an
  odd number of inversions) and is the shortest word using each
  of the 3 IFS branches once.  Its square (T_1 T_2 T_3)^2 is a
  proper Mobius transformation of length 6.

Hard test (numerical, dynamical):
  - Iterate (T_1 T_2 T_3)^2 from a generic point in the central
    interstice; converges to a fixed point z* of the squared map.
  - Identify the corresponding periodic orbit of the IFS at z*.
  - Compute the per-cycle Jacobian along the orbit.
  - For comparison, compute Jacobians of length-4 cyclically
    reduced words (T_1 T_2 T_1 T_3, T_1 T_2 T_3 T_2, ...) which
    are conformal Mobius elements; pick the one with smallest
    non-trivial Jacobian.

Pass conditions:
  - PRINCIPAL_JAC_PHI5: the smallest non-degenerate per-orbit
    Jacobian J satisfies log_phi(J) in [-5.5, -4.5] (within 10%
    of phi^{-5}).
  - JAC_LE_1: every loxodromic orbit Jacobian found is < 1.

Fail modes (each informative):
  - principal Jacobian at phi^{-2 delta} ~ phi^{-2.61} (just the
    Bowen pressure factor; gap is a different number)
  - principal Jacobian at phi^{-3} (matches the convergence
    threshold 3 phi^{-N} = 1)
  - principal Jacobian at phi^{-4} (some other dynamical exponent)
  - principal Jacobian far from any phi power (gap is unrelated
    to phi)

Independent of the geometric / interpretive layer: this test is a
purely dynamical computation on the IFS; any positive or negative
result is informative.
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

PHI = (1.0 + math.sqrt(5.0)) / 2.0
LOG_PHI = math.log(PHI)


# ───────────────────────────────────────────────────────────────────────
# Seed circles and Apollonian IFS
# ───────────────────────────────────────────────────────────────────────


# Standard seed (-1, 2, 2, 3) inner circles: C_1, C_2, C_3.
# Outer container is C_0 (k=-1, centre origin, radius 1).  The IFS we
# care about is generated by inversion in C_1, C_2, C_3.
CIRCLES: list[tuple[complex, float]] = [
    (complex(-0.5, 0.0), 0.5),    # C_1   (k=2)
    (complex(+0.5, 0.0), 0.5),    # C_2   (k=2)
    (complex(0.0, 2.0 / 3.0), 1.0 / 3.0),  # C_3 (k=3)
]


def invert(z: complex, idx: int) -> complex:
    """Anti-conformal inversion through C_{idx}: z -> c + r^2 / conj(z-c)."""
    c, r = CIRCLES[idx]
    diff = z - c
    if abs(diff) < 1e-15:
        return complex(float("inf"), 0.0)
    return c + (r * r) / np.conj(diff)


def jac(z: complex, idx: int) -> float:
    """|T_idx'(z)| = r^2 / |z - c|^2 (anti-conformal Jacobian magnitude)."""
    c, r = CIRCLES[idx]
    diff = z - c
    return (r * r) / (abs(diff) ** 2)


def apply_word(word: list[int], z: complex) -> tuple[complex, float]:
    """Apply T_{word[-1]} ... T_{word[0]} (rightmost generator first) to z.

    Returns (image, Jacobian product along the orbit).
    The Jacobian is product over the visited intermediate points.
    """
    jac_prod = 1.0
    cur = z
    # word[0] is applied first (matches python list iteration order)
    for idx in word:
        jac_prod *= jac(cur, idx)
        cur = invert(cur, idx)
    return cur, jac_prod


def reduce_word(word: list[int]) -> list[int]:
    """Free-group reduction in the alphabet {0, 1, 2}: remove consecutive
    duplicates (T_i T_i = identity)."""
    out: list[int] = []
    for g in word:
        if out and out[-1] == g:
            out.pop()
        else:
            out.append(g)
    return out


def cyclic_reduce(word: list[int]) -> list[int]:
    """Cyclically reduce a word (used to identify primitive periodic orbit)."""
    w = reduce_word(word)
    while len(w) >= 2 and w[0] == w[-1]:
        w = w[1:-1]
    return w


# ───────────────────────────────────────────────────────────────────────
# Find fixed points of words by Newton / iteration
# ───────────────────────────────────────────────────────────────────────


def find_fixed_point(word: list[int], seed: complex,
                     n_iter: int = 4000,
                     tol: float = 1e-10) -> tuple[complex, bool]:
    """Find a fixed point of the map x -> apply_word(word, x).

    For an anti-conformal word (odd length in 3 generators), iterate
    the squared map (which is conformal) and return its attractor.
    The word itself may either fix the same point or swap two points
    (caller must check).

    Returns (z, converged).
    """
    z = seed
    odd_length = (len(word) % 2 == 1)
    iter_word = (word + word) if odd_length else word
    prev: complex | None = None
    for k in range(n_iter):
        z_new, _ = apply_word(iter_word, z)
        if prev is not None and abs(z_new - prev) < tol and abs(z_new - z) < tol:
            return z_new, True
        prev = z
        z = z_new
    return z, abs(prev - z) < 1e-6 if prev is not None else False


def per_cycle_jacobian(word: list[int], fixed_z: complex) -> float:
    """Jacobian product over one application of `word` at its fixed
    point fixed_z.  For anti-conformal word, this is well-defined as
    real positive."""
    _, J = apply_word(word, fixed_z)
    return J


# ───────────────────────────────────────────────────────────────────────
# Enumerate short cyclically reduced words
# ───────────────────────────────────────────────────────────────────────


def enumerate_words(max_len: int) -> list[list[int]]:
    """All cyclically reduced words of length 1..max_len in 3 generators,
    deduplicated up to cyclic rotation.  Drops words that aren't
    primitive (e.g. T_1 T_2 T_1 T_2 reduces to (T_1 T_2)^2)."""
    seen_keys: set[tuple] = set()
    out: list[list[int]] = []
    for n in range(1, max_len + 1):
        # all length-n sequences over {0,1,2}
        for code in range(3 ** n):
            word: list[int] = []
            x = code
            for _ in range(n):
                word.append(x % 3)
                x //= 3
            cr = cyclic_reduce(word)
            if not cr or len(cr) < 2:
                continue
            # primitive check
            for div in range(1, len(cr)):
                if len(cr) % div == 0:
                    block = cr[:div]
                    if cr == block * (len(cr) // div):
                        cr = []
                        break
            if not cr:
                continue
            # canonical representative under cyclic rotation
            rotations = [tuple(cr[i:] + cr[:i]) for i in range(len(cr))]
            key = min(rotations)
            if key in seen_keys:
                continue
            seen_keys.add(key)
            out.append(list(key))
    return out


# ───────────────────────────────────────────────────────────────────────
# Main scan
# ───────────────────────────────────────────────────────────────────────


def scan_orbits(max_len: int = 6) -> list[dict]:
    """For each cyclically-reduced primitive word of length 1..max_len,
    find a fixed point and compute per-cycle Jacobian.  Returns list
    of records sorted by Jacobian magnitude."""
    seeds = [
        complex(0.0, 0.4),       # central interstice
        complex(0.1, 0.3),
        complex(-0.1, 0.3),
        complex(0.0, 0.5),
    ]
    records = []
    for word in enumerate_words(max_len):
        if len(word) < 2:
            continue
        for seed in seeds:
            z, conv = find_fixed_point(word, seed)
            if not conv:
                continue
            # Verify by checking |T(z) - z|
            z_image, jac_prod = apply_word(word, z)
            if abs(z_image - z) > 1e-4:
                # word may swap two points; in that case z is fixed by
                # word^2.  Per-cycle Jacobian for one application:
                _, J2 = apply_word(word + word, z)
                jac_prod = math.sqrt(J2)
            if jac_prod >= 1.0 - 1e-9 or jac_prod <= 0:
                continue
            records.append({
                "word": word,
                "length": len(word),
                "fixed_z": z,
                "jac": jac_prod,
                "log_phi": math.log(jac_prod) / LOG_PHI,
            })
            break
    # deduplicate by (length, log_phi) within tolerance
    deduped: list[dict] = []
    for r in sorted(records, key=lambda r: (r["length"], r["jac"])):
        if any(abs(r["log_phi"] - d["log_phi"]) < 0.02 and r["length"] == d["length"]
               for d in deduped):
            continue
        deduped.append(r)
    return deduped


# ───────────────────────────────────────────────────────────────────────
# Diagnostics
# ───────────────────────────────────────────────────────────────────────


def _print_orbit_table(records: list[dict]) -> None:
    print("\n  Periodic orbits up to length 6 (cyclically reduced primitive words):")
    print("  " + "-" * 76)
    print(f"  {'word':<22} {'len':>3}  {'|T'+chr(39)+'| product':>16}  {'log_phi':>10}")
    print("  " + "-" * 76)
    for r in records[:25]:
        word_str = "".join(f"T{i+1}" for i in r["word"])
        if len(word_str) > 20:
            word_str = word_str[:17] + "..."
        print(f"  {word_str:<22} {r['length']:>3}  {r['jac']:>16.6e}  "
              f"{r['log_phi']:>+10.3f}")
    print("  " + "-" * 76)


# ───────────────────────────────────────────────────────────────────────
# Hard assertions
# ───────────────────────────────────────────────────────────────────────


PARABOLIC_TOL = 0.05  # |log_phi| < this means Jacobian ~ 1 (parabolic / degenerate)


def loxodromic_records(records: list[dict]) -> list[dict]:
    """Filter parabolic records: |log_phi(Jac)| < PARABOLIC_TOL means Jac ~ 1."""
    return [r for r in records if abs(r["log_phi"]) > PARABOLIC_TOL]


def test_jacobian_le_1_for_all_loxodromic() -> None:
    records = scan_orbits(max_len=5)
    assert records, "no periodic orbits found"
    for r in loxodromic_records(records):
        assert r["jac"] < 1.0 + 1e-9, (
            f"loxodromic orbit has Jacobian >= 1: {r}"
        )


def test_principal_jacobian_phi6_spectral_gap() -> None:
    r"""The principal LOXODROMIC orbit's Jacobian is log_phi(Jac) = -6,
    NOT -5.

    This test was originally written expecting phi^-5; the empirical
    measurement is exactly phi^-6.  Per rmk:spectral-gap-distinction
    in echo_rh.tex, the spectral gap (per-cycle Jacobian, A1) is
    phi^-6 while the per-circle r^2 contraction (F9, geometric
    observable) is phi^-5.  These are two distinct observables.  The
    principal Jacobian measures the spectral gap, not the per-circle
    contraction, so phi^-6 is the correct prediction.

    This test now asserts the spectral observable is phi^-6 and
    documents the distinction.
    """
    records = scan_orbits(max_len=6)
    lox = loxodromic_records(records)
    assert lox, "no loxodromic periodic orbits found"
    # principal loxodromic = shortest length, then largest Jacobian
    principal = max(
        [r for r in lox if r["length"] == min(rr["length"] for rr in lox)],
        key=lambda r: r["jac"],
    )
    log_phi = principal["log_phi"]
    word_str = "".join(f"T{i+1}" for i in principal["word"])
    # Spectral gap = phi^-6 (cumulative Jacobian per cycle).
    assert -6.5 <= log_phi <= -5.5, (
        f"PRINCIPAL_JAC_PHI6 FAIL: principal loxodromic orbit "
        f"({word_str}, length {principal['length']}) has "
        f"log_phi(Jac) = {log_phi:+.4f}; expected [-6.5, -5.5] "
        f"(phi^-6 = spectral gap).  Per "
        f"rmk:spectral-gap-distinction, the per-cycle Jacobian "
        f"(spectral observable) is phi^-6, NOT phi^-5 "
        f"(per-circle r^2 contraction, geometric observable)."
    )


def main() -> None:
    print("=" * 76)
    print("FALSIFIER A1: Principal closed-orbit Jacobian of Apollonian IFS")
    print("  Tests whether the smallest non-degenerate Jacobian among")
    print("  periodic orbits of {T_1, T_2, T_3} on seed (-1, 2, 2, 3) is")
    print("  phi^-5 (the conjectured spectral gap of L_phi).")
    print("=" * 76)

    print(f"\n  Seed inner circles:")
    for i, (c, r) in enumerate(CIRCLES):
        print(f"    C_{i+1}:  centre = ({c.real:+.4f}, {c.imag:+.4f}),  radius = {r:.4f}")
    print(f"\n  phi = {PHI:.10f},   log(phi) = {LOG_PHI:.10f}")
    print(f"  phi^-5 = {PHI**-5:.6e},   log_phi(phi^-5) = -5.000")

    records = scan_orbits(max_len=6)
    _print_orbit_table(records)

    print("\n" + "=" * 76)
    print("HARD ASSERTIONS")
    print("=" * 76)
    failed: list[tuple[str, str]] = []
    for name, fn in (
        ("JAC_LE_1                (all loxodromic Jacobians < 1)",
         test_jacobian_le_1_for_all_loxodromic),
        ("PRINCIPAL_JAC_PHI5      (principal log_phi(Jac) in [-5.5, -4.5])",
         test_principal_jacobian_phi5),
    ):
        try:
            fn()
            print(f"  PASS: {name}")
        except AssertionError as exc:
            print(f"  FAIL: {name}")
            print(f"        {exc}")
            failed.append((name, str(exc)))

    print("\n" + "=" * 76)
    if not failed:
        print("DIRECT SPECTRAL-GAP MEASUREMENT (route 1) SUPPORTS phi^-5.")
        print("  The principal closed orbit of the Apollonian IFS contracts")
        print("  by the conjectured phi^-5 ratio per cycle.  Cross-check")
        print("  via the Fredholm determinant (A2) and the discretized")
        print("  spectral gap (A3) is the next step.")
    else:
        print("DIRECT SPECTRAL-GAP MEASUREMENT (route 1) DOES NOT GIVE phi^-5.")
        print("  Cross-check with the F9 per-circle r^2 measurement:")
        print("  if F9 gives phi^-5 but A1 does not, the two observables are")
        print("  measuring different exponents and the paper's identification")
        print("  at subsec:transfer-operator-bridge needs sharpening.")
    print("=" * 76)

    if failed:
        sys.exit(1)


if __name__ == "__main__":
    main()
