"""Cl(1,1) algebra tests for the Collatz extension.

The Collatz Clifford algebra Cl(1,1) is the 4-dimensional algebra
generated by {1, e1, e2, e1*e2} with signature

    e1^2 = +1   (binary contraction direction; grace)
    e2^2 = -1   (triadic expansion direction; nilpotent)
    e1*e2 = -e2*e1

The volume element omega = e1*e2 satisfies omega^2 = +1.

This file verifies:
  - Multiplication table is associative and matches Cl(1,1) signature
  - Anticommutation e1*e2 = -e2*e1 holds
  - omega^2 = +1
  - Decomposition into even (R + R*omega) and odd (R*e1 + R*e2) parts
  - Reverse and grade involutions are well-defined

Pass conditions:
  - SIGNATURE: e1^2 = 1, e2^2 = -1
  - ANTICOMMUTE: e1*e2 + e2*e1 = 0
  - OMEGA_SQ: omega^2 = +1
  - ASSOCIATIVE: (a*b)*c == a*(b*c) for random triples
  - REVERSE_INVOLUTIVE: rev(rev(x)) == x for random x
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))


# ────────────────────────────────────────────────────────────────────────
# Cl(1,1) representation as 4-vector (s, v1, v2, b)
# basis order: 1, e1, e2, e1*e2
# ────────────────────────────────────────────────────────────────────────


def cl11_mul(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    """Multiply two Cl(1,1) elements.

    Coordinates: a = a0 + a1*e1 + a2*e2 + a3*e1e2.
    Relations:
        e1^2 = +1,  e2^2 = -1,  e1e2 = -e2e1.
    Derived:
        omega = e1 e2,    omega^2 = -e1^2 e2^2 = +1
        e1*omega = +e2,   omega*e1 = -e2
        e2*omega = +e1,   omega*e2 = -e1
    """
    a0, a1, a2, a3 = a
    b0, b1, b2, b3 = b
    c0 = a0 * b0 + a1 * b1 - a2 * b2 + a3 * b3
    c1 = a0 * b1 + a1 * b0 + a2 * b3 - a3 * b2
    c2 = a0 * b2 + a1 * b3 + a2 * b0 - a3 * b1
    c3 = a0 * b3 + a1 * b2 - a2 * b1 + a3 * b0
    return np.array([c0, c1, c2, c3], dtype=np.float64)


def cl11_basis() -> dict[str, np.ndarray]:
    return {
        "1":   np.array([1.0, 0.0, 0.0, 0.0]),
        "e1":  np.array([0.0, 1.0, 0.0, 0.0]),
        "e2":  np.array([0.0, 0.0, 1.0, 0.0]),
        "w":   np.array([0.0, 0.0, 0.0, 1.0]),  # omega = e1 e2
    }


def cl11_reverse(a: np.ndarray) -> np.ndarray:
    """Clifford reversal: 1 -> 1, e1 -> e1, e2 -> e2, e1e2 -> e2e1 = -e1e2."""
    return np.array([a[0], a[1], a[2], -a[3]], dtype=np.float64)


def cl11_norm_sq(a: np.ndarray) -> float:
    """<a * rev(a)>_0, the scalar part of a * reverse(a)."""
    return float(cl11_mul(a, cl11_reverse(a))[0])


def cl11_close(a: np.ndarray, b: np.ndarray, tol: float = 1e-12) -> bool:
    return bool(np.allclose(a, b, atol=tol, rtol=0.0))


# ────────────────────────────────────────────────────────────────────────
# Tests
# ────────────────────────────────────────────────────────────────────────


def test_signature_e1_squared_is_plus_one() -> None:
    B = cl11_basis()
    e1_sq = cl11_mul(B["e1"], B["e1"])
    assert cl11_close(e1_sq, B["1"]), f"e1^2 != 1: got {e1_sq}"


def test_signature_e2_squared_is_minus_one() -> None:
    B = cl11_basis()
    e2_sq = cl11_mul(B["e2"], B["e2"])
    expected = -B["1"]
    assert cl11_close(e2_sq, expected), f"e2^2 != -1: got {e2_sq}"


def test_anticommutation_e1_e2() -> None:
    B = cl11_basis()
    a = cl11_mul(B["e1"], B["e2"])
    b = cl11_mul(B["e2"], B["e1"])
    s = a + b
    assert cl11_close(s, np.zeros(4)), f"e1 e2 + e2 e1 != 0: got {s}"


def test_omega_equals_e1_e2() -> None:
    B = cl11_basis()
    e1e2 = cl11_mul(B["e1"], B["e2"])
    assert cl11_close(e1e2, B["w"]), f"e1*e2 != omega basis vector: {e1e2}"


def test_omega_squared_is_plus_one() -> None:
    B = cl11_basis()
    w_sq = cl11_mul(B["w"], B["w"])
    assert cl11_close(w_sq, B["1"]), f"omega^2 != 1: got {w_sq}"


def test_associativity_random_triples() -> None:
    rng = np.random.default_rng(1729)
    failures = 0
    n_trials = 200
    for _ in range(n_trials):
        a, b, c = rng.normal(size=(3, 4))
        ab_c = cl11_mul(cl11_mul(a, b), c)
        a_bc = cl11_mul(a, cl11_mul(b, c))
        if not cl11_close(ab_c, a_bc, tol=1e-10):
            failures += 1
    assert failures == 0, f"Associativity violated in {failures}/{n_trials} trials"


def test_reverse_is_involutive() -> None:
    rng = np.random.default_rng(42)
    for _ in range(50):
        a = rng.normal(size=4)
        assert cl11_close(cl11_reverse(cl11_reverse(a)), a)


def test_unit_squared_is_unit() -> None:
    B = cl11_basis()
    one_sq = cl11_mul(B["1"], B["1"])
    assert cl11_close(one_sq, B["1"])


def test_even_subalgebra_closure() -> None:
    """Cl+(1,1) = span{1, omega} should be closed under multiplication."""
    B = cl11_basis()
    rng = np.random.default_rng(7)
    for _ in range(50):
        a = rng.normal() * B["1"] + rng.normal() * B["w"]
        b = rng.normal() * B["1"] + rng.normal() * B["w"]
        c = cl11_mul(a, b)
        assert abs(c[1]) < 1e-12 and abs(c[2]) < 1e-12, (
            f"Even subalgebra not closed: {a} * {b} = {c}"
        )


def main() -> None:
    print("=" * 72)
    print("Cl(1,1) ALGEBRA TESTS (Collatz extension)")
    print("=" * 72)

    B = cl11_basis()
    print("\n  Multiplication table for {1, e1, e2, omega}:")
    names = ["1", "e1", "e2", "w"]
    print("  " + " " * 8 + "  ".join(f"{n:>8}" for n in names))
    for ni in names:
        row = []
        for nj in names:
            prod = cl11_mul(B[ni], B[nj])
            # Identify which basis vector (or scalar multiple) the product is
            best = None
            best_v = 0.0
            for nk, vk in B.items():
                inner = float(np.dot(prod, vk))
                if abs(inner) > abs(best_v):
                    best_v = inner
                    best = nk
            sign = "+" if best_v >= 0 else "-"
            row.append(f"{sign}{best}")
        print(f"  {ni:>6}: " + "  ".join(f"{r:>8}" for r in row))

    print(f"\n  e1^2  = {cl11_mul(B['e1'], B['e1'])} (expect +1)")
    print(f"  e2^2  = {cl11_mul(B['e2'], B['e2'])} (expect -1)")
    print(f"  e1*e2 = {cl11_mul(B['e1'], B['e2'])} (expect omega)")
    print(f"  e2*e1 = {cl11_mul(B['e2'], B['e1'])} (expect -omega)")
    print(f"  w^2   = {cl11_mul(B['w'], B['w'])} (expect +1)")

    print("\n  Running pytest-style checks ...")
    for fn in [
        test_signature_e1_squared_is_plus_one,
        test_signature_e2_squared_is_minus_one,
        test_anticommutation_e1_e2,
        test_omega_equals_e1_e2,
        test_omega_squared_is_plus_one,
        test_associativity_random_triples,
        test_reverse_is_involutive,
        test_unit_squared_is_unit,
        test_even_subalgebra_closure,
    ]:
        try:
            fn()
            print(f"  PASS: {fn.__name__}")
        except AssertionError as e:
            print(f"  FAIL: {fn.__name__}: {e}")
            raise

    print("\n  ALL CL(1,1) ALGEBRA TESTS PASSED.")


if __name__ == "__main__":
    main()
